-- ProcessId: ptvbacSmqJPfgCXxPc9bcobs5Th2B_SxTf81vRNkRzk

-- Test process
LLAMA_TOKEN_PROCESS = "Btm_9_fvwb7eXbQ2VswA4V19HxYWnFsYRB4gIl3Dahw"

-- LIVE
WRAPPED_ARWEAVE_TOKEN_PROCESS = "xU9zFkq3X2ZQ6olwNVvr1vUWIjc3kXTWr7xKQD6dh10"

LLAMA_KING_PROCESS = "X3Gw5VxMp61BWqATEdnf5AXHYN5cz1qyI9vjAYW0U94"

-- Same as LlamaFed
LLAMA_FED_CHAT_PROCESS = "QIFgbqEmk5MyJy01wuINfcRP_erGNNbhqHRkAQjxKgg"

LLAMA_ROUTER_PROCESS_ID = "CNYmT-nVug2kdURhI0zuLu6kPkOQrchAzV8mIInmKws"
