-- Name: LlamaBankerDummy2
-- ProcessId: ptvbacSmqJPfgCXxPc9bcobs5Th2B_SxTf81vRNkRzk

-- LIVE
WAITLIST_PROCESS = "2dFSGGlc5xJb0sWinAnEFHM-62tQEbhDzi1v5ldWX5k"

-- Test process
LLAMA_TOKEN_PROCESS = "pazXumQI-HPH7iFGfTC-4_7biSnqz_U67oFAGry5zUY"

-- LIVE
-- WRAPPED_ARWEAVE_TOKEN_PROCESS = "xU9zFkq3X2ZQ6olwNVvr1vUWIjc3kXTWr7xKQD6dh10"

LLAMA_KING_PROCESS = "vkMZYPIUQAktEy6etxg3ALoLfqxHbq1tkUsp95Lb3wE"

-- Same as LlamaFed
LLAMA_FED_CHAT_PROCESS = "QIFgbqEmk5MyJy01wuINfcRP_erGNNbhqHRkAQjxKgg"

MAXIMUM_PETITIONS_PER_DAY = 3
