-- Name: LlamaKingDev
-- ProcessId: X3Gw5VxMp61BWqATEdnf5AXHYN5cz1qyI9vjAYW0U94

WRAPPED_ARWEAVE_TOKEN_PROCESS = "xU9zFkq3X2ZQ6olwNVvr1vUWIjc3kXTWr7xKQD6dh10"

LLAMA_BANKER_PROCESS = "" -- TODO

LLAMA_FED_CHAT_PROCESS = "QIFgbqEmk5MyJy01wuINfcRP_erGNNbhqHRkAQjxKgg"

LLAMA_ROUTER_PROCESS_ID = "CNYmT-nVug2kdURhI0zuLu6kPkOQrchAzV8mIInmKws"
