-- ProcessId: ptvbacSmqJPfgCXxPc9bcobs5Th2B_SxTf81vRNkRzk

HOURLY_EMISSION_LIMIT = 1000000
LLAMA_TOKEN_PROCESS = "Btm_9_fvwb7eXbQ2VswA4V19HxYWnFsYRB4gIl3Dahw"

-- AO CRED for now
WRAPPED_ARWEAVE_TOKEN_PROCESS = "Sa0iBLPNyJQrwpTTG-tWLQU-1QeUAJA73DdxGGiKoJc"

LLAMA_KING_PROCESS = "kPjfXLFyjJogxGRRRe2ErdYNiexolpHpK6wGkz-UPVA"

-- Same as LlamaFed
LLAMA_FED_CHAT_PROCESS = "QIFgbqEmk5MyJy01wuINfcRP_erGNNbhqHRkAQjxKgg"
